#ifndef MAINFRAMEDEFINE_H
#define MAINFRAMEDEFINE_H

#define CMD_Settings "Settings"
#define CMD_Theme "Theme"
#define CMD_DefaultStyle "DefaultStyle"
#define CMD_Help "Help"
#define CMD_AppHelp "AppHelp"
#define CMD_AppAbout "AppAbout"
#define CMD_AppAboutQt "AppAboutQt"
#define CMD_FileNew "FileNew"
#define CMD_FileNewWindow "FileNewWindow"
#define CMD_FileOpen "FileOpen"
#define CMD_FileSave "FileSave"
#define CMD_FileSaveAs "FileSaveAs"
#define CMD_FileReload "FileReload"
#define CMD_FileExplore "FileExplore"
#define CMD_AppExit "AppExit"
#define CMD_FileSave "FileSave"
#define CMD_EditUndo "EditUndo"
#define CMD_EditRedo "EditRedo"
#define CMD_EditPaste "EditPaste"
#define CMD_EditCut "EditCut"
#define CMD_EditCopy "EditCopy"
#define CMD_EditUndo "EditUndo"
#define CMD_EditRedo "EditRedo"
#define CMD_EditMarkAll "EditMarkAll"
#define CMD_EditAddRemoveComment "EditAddRemoveComment"
#define CMD_EditSelectAll "EditSelectAll"
#define CMD_EditGoToLine "EditGoToLine"
#define CMD_EditCapitalCase "EditCapitalCase"
#define CMD_EditLowerCase "EditLowerCase"
#define CMD_EditTitalCase "EditTitalCase"
#define CMD_EditFind "EditFind"
#define CMD_EditFindPrevious "EditFindPrevious"
#define CMD_EditFindNext "EditFindNext"
#define CMD_EditReplace "EditReplace"
#define CMD_EditDateTime "EditDateTime"
#define CMD_CodeAnsi "CodeAnsi"
#define CMD_CodeUtf8 "CodeUtf8"
#define CMD_CodeUtf16 "CodeUtf16"
#define CMD_CodeUtf16BigEnding "CodeUtf16BigEnding"
#define CMD_CodeConvertToAnsi "CodeConvertToAnsi"
#define CMD_CodeConvertToUtf8Bom "CodeConvertToUtf8Bom"
#define CMD_CodeConvertToUtf8WithoutBom "CodeConvertToUtf8WithoutBom"
#define CMD_CodeConvertToUtf16 "CodeConvertToUtf16"
#define CMD_CodeConvertToUtf16Be "CodeConvertToUtf16Be"
#define CMD_WordWrap "WordWrap"
#define CMD_ShowLineNumber "ShowLineNumber"
#define CMD_ShowReturnMark "ShowReturnMark"
#define CMD_ReturnMarkCRLF "ReturnMarkCRLF"
#define CMD_ReturnMarkCR "ReturnMarkCR"
#define CMD_ReturnMarkLF "ReturnMarkLF"
#define CMD_WordWrapModeWord "WordWrapModeWord"
#define CMD_WordWrapModeCharactor "WordWrapModeCharactor"
#define CMD_WordWrapModeSpace "WordWrapModeSpace"
#define CMD_FormatFont "FormatFont"
#define CMD_FormatLanguage "FormatLanguage"
#define CMD_AlwaysOnTop "AlwaysOnTop"
#define CMD_ShowStatusBar "ShowStatusBar"
#define CMD_ZoomIn "ZoomIn"
#define CMD_ZoomOut "ZoomOut"
#define CMD_ZoomDefault "ZoomDefault"
#define CMD_HexView "HexView"
#define CMD_FileCompareBinary "FileCompareBinary"
#define CMD_CodeConvertBatch "CodeConvertBatch"
#define CMD_CodeConvert "CodeConvert"
#define CMD_MonitorMode "MonitorMode"
#define CMD_Options "Options"

#include <QScreen>
#include <QGuiApplication>

//将一个像素值根据当前屏幕DPI设置进行等比放大
inline int DPI(int x)
{
    return QGuiApplication::primaryScreen()->logicalDotsPerInch() * x / 96;
}


#endif // MAINFRAMEDEFINE_H
